### ISSUE TITLE
Contribute to TLA+ examples

### ISSUE THREAD

**Issue by lemmy** [Alexander-N/tla-specs#1]
Please consider contributing your specs to the [TLA+ examples](https://github.com/tlaplus/Examples) or have them listed on [Awesome TLA+](https://github.com/tlaplus/awesome-tlaplus)?  Also, it would be great to disseminate the information on how to work with ShiViz.  [Here is another example of a vector clock](https://github.com/tlaplus/Examples/commit/ee10c6ed1c65f1002c8ad402edceeffcf1a833ea) whose output has since been included in [ShiViz upstream](https://bestchai.bitbucket.io/shiviz/) ("EWD998").

**Comment by Alexander-N** [comment]
Of course, which ones do you think are suitable for the examples, maybe [crdt-bug](https://github.com/Alexander-N/tla-specs/tree/main/crdt-bug) and [asyncio-lock](https://github.com/Alexander-N/tla-specs/tree/main/asyncio-lock)?

I'm not sure about ShiViz, I found both the use and the output a bit too complicated. From the [one bug I filed](https://github.com/DistributedClocks/shiviz/issues/168) I get the impression that it also might not be super actively maintained.

**Comment by Alexander-N** [comment]
I would be happy to see this repo listed on [Awesome TLA+](https://github.com/tlaplus/awesome-tlaplus) but there seems no section where it would fit naturally. Maybe applications or some new "misc" section?

**Comment by lemmy** [comment]
Let's pretend these are "articles" that can go into https://github.com/tlaplus/awesome-tlaplus#tla-blog-posts-and-articles ?

A ShiViz visualization might appear complicated, but isn't this the result of a complicated trace? At any rate, ShiViz is definitely maintained.

**Comment by Alexander-N** [comment]
> A ShiViz visualization might appear complicated, but isn't this the result of a complicated trace?

Maybe complicated is not the right word, but an interactive tool can be a bit much when you simply need an image with some arrows to communicate a problem TLC found.
